default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: handbook_development
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5433") %>
  username: <%= ENV.fetch("POSTGRES_USER", "handbook") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "handbook") %>

test:
  <<: *development
  database: handbook_test

production:
  primary: &primary_production
    <<: *default
    database: handbook_production
    username: handbook
    password: <%= ENV["HANDBOOK_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: handbook_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: handbook_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: handbook_production_cable
    migrations_paths: db/cable_migrate
