service: handbook
image: denvercriticalmass/handbook

servers:
  web:
    - 192.168.0.1

proxy:
  ssl: true
  hosts:
    - denvercriticalmass.org
    - www.denvercriticalmass.org

registry:
  server: ghcr.io
  username: denvercriticalmass
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - RESEND_API_KEY
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
  clear:
    SOLID_QUEUE_IN_PUMA: true
    APP_HOST: denvercriticalmass.org
    SUPERADMIN_EMAIL: joe@joesak.com
    POSTGRES_HOST: handbook-db

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "handbook_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: postgres:18.6
    host: 192.168.0.1
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: handbook
        POSTGRES_DB: handbook_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql
