North America:
  Denver:
  Albuquerque:
  Chicago: https://www.instagram.com/chicritmass/
  Raleigh:
  Greensboro:
  Charlotte:
  Gainesville:
  Orlando:
  Austin:
  Houston:
  McAllen:
  Fort Worth:
  Boise:
  Bakersfield:
  Seattle:
  San Francisco: https://sfcriticalmass.com/
  Edmonton:
  Calgary:
  Montreal: https://massecritiquemtl.ca/en/about
  Kanata:
  New London:
  New Orleans:
  El Paso:
  Guadalajara: https://gdlenbici.org/paseo-de-todas-y-todos/
  Guatemala City:
  Nanaimo:
  Washington DC:

South America:
  Buenos Aires: https://www.instagram.com/masacriticaba/
  Rio de Janeiro:
  Sao Paulo:
  Porto Alegre:
  Dourados:
  Recife:
  Caxias do Sul:
  Goiania:
  Guayaquil:
  Montevideo:
  Tarija:
  Salvador:
  Joao Pessoa:
  Marilia:
  Manaus:
  Brasilia:
  Campinas:
  Natal:

Europe:
  London: https://network23.org/criticalmasslondon/
  Belfast:
  Aberdeen:
  Dundee:
  Inverness:
  Norwich:
  Dublin:
  Antwerp:
  Brussels:
  Namur:
  Lorient:
  Lyon:
  Millau:
  Montpellier:
  Nantes:
  Nice:
  Saint-Brieuc:
  Toulouse:
  Bordeaux:
  Lisbon:
  Porto:
  Valencia:
  Granada:
  Pamplona:
  Gasteiz:
  Madrid: https://madrid.bicicritica.com/en/frequently-asked-questions
  Rome:
  Firenze:
  Milano:
  Genova:
  Cremona:
  Parma:
  Ticino:
  Basel:
  Bern:
  Luzern:
  Zurich:
  Winti:
  Graz:
  Vienna: https://www.instagram.com/criticalmasswien/
  St. Veit/Glan:
  Hamburg:
  Bremen:
  Bonn:
  Braunschweig:
  Dortmund:
  Dresden:
  Duisburg:
  Dusseldorf:
  Erfurt:
  Erlangen:
  Freising:
  Hildesheim:
  Jena:
  Kassel:
  Ludenscheid:
  Luneburg:
  Mainz:
  Munich:
  Munster:
  Neuss:
  Offenbach:
  Oldenburg:
  Pforzheim:
  Saarbrucken:
  Schussental:
  Stuttgart:
  Trier:
  Wolfsburg:
  Wuppertal:
  Prague:
  Czestochowa:
  Bratislava:
  Nitra:
  Timisoara:
  Istanbul:
  Izmir:
  Bergen:
  Gondomar:
  Brescia:
  Bergamo:
  Viana do Castelo:
  Treviso:

Africa:
  Nairobi: https://www.criticalmassnairobi.org/
  Mombasa:
  Nakuru:
  Thika:
  Cape Town:
  Johannesburg:
  Durban:
  Casablanca:
  Safi:
  Dar es Salaam:

Asia:
  Seoul: https://www.instagram.com/criticalmassseoul/
  Tokyo:
  Nagoya:
  Jakarta:
  Bandung:
  Bekasi:
  Cimahi:
  Kendari:
  Sukabumi:
  Kuala Lumpur:
  Manila:
  Kathmandu:
  Karachi:
  Lahore:

Oceania:
  Melbourne: https://criticalmass.melbourne/
  Sydney:
  Brisbane:
  Adelaide:
  Perth:
  Canberra:
  Hobart:
  Dunedin:
